name: Security Scan

on:
  push:
    paths:
      - 'packages/**'
      - 'packages/mpkg.packages.json'
  pull_request:
    paths:
      - '**'

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Run security scan
        id: scan
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            python scripts/security_scan.py --throttle 3 | tee scan.log
          else
            python scripts/security_scan.py --only-not-scanned --throttle 3 | tee scan.log
          fi
        continue-on-error: true
      - name: Upload scan log
        uses: actions/upload-artifact@v4
        with:
          name: scan-log
          path: scan.log
      - name: Label PR if suspicious
        if: steps.scan.outcome == 'failure'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const labelName = 'pending-investigation';
            async function ensureLabel() {
              try {
                await github.rest.issues.getLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: labelName
                });
              } catch (e) {
                if (e.status === 404) {
                  await github.rest.issues.createLabel({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    name: labelName,
                    color: 'ff0000',
                    description: 'Package flagged for investigation'
                  });
                } else {
                  throw e;
                }
              }
            }
            if (context.eventName === 'pull_request') {
              await ensureLabel();
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: [labelName]
              });
            }
